version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - "80:80"
    networks: 
      - testnode-network

  users-service:
    image: users-service
    container_name: users_service
    ports:
      - "8123:8123"
    networks: 
      - testnode-network

  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "users"
      MYSQL_USER: "users_service"
      MYSQL_PASSWORD: "123"
    networks: 
      - testnode-network

networks:
  testnode-network:
